src/Tap2020Demo.Web/Areas/Account/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tap2020Demo.Web.Areas.Account.Models
{
    public class LoginViewModel
    {
        public string Username { get; set; }

        public string Password { get; set; }

        public string ReturnUrl { get; set; }
    }
}

src/Tap2020Demo.Web/Areas/BackOffice/Models/CreateCustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tap2020Demo.Web.Areas.BackOffice.Models
{
    public class CreateCustomerViewModel
    {
    }
}

src/Tap2020Demo.Web/Areas/BackOffice/Models/SearchCustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Uaic.Tap2020Demo.Core;

namespace Tap2020Demo.Web.Areas.BackOffice.Models
{
    public class SearchCustomersViewModel
    {
        public SearchCustomersViewModel()
        {
            Results = Enumerable.Empty<Customer>();
        }

        public string SearchTerm { get; set; }

        public IEnumerable<Customer> Results { get; internal set; }
    }
}

src/Tap2020Demo.Web/Models/ErrorViewModel.cs
using System;

namespace Tap2020Demo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Tap2020Demo.Web/Areas/Account/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Tap2020Demo.Web.Areas.Account.Models;
using Uaic.Tap2020Demo.Core.Identity;

namespace Tap2020Demo.Web.Areas.Account.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly SignInManager<User> _signInManager;

        public AuthenticationController(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var result = await _signInManager.PasswordSignInAsync(viewModel.Username, viewModel.Password, false, false);
            if (!result.Succeeded)
            {
                ModelState.AddModelError(String.Empty, "Invalid login attempt");
                return View(viewModel);
            }

            if (!String.IsNullOrEmpty(viewModel.ReturnUrl) && Url.IsLocalUrl(viewModel.ReturnUrl))
            {
                return Redirect(viewModel.ReturnUrl);
            }

            return Redirect("/");
        }
    }
}

src/Tap2020Demo.Web/Areas/BackOffice/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tap2020Demo.Web.Areas.BackOffice.Models;
using Uaic.Tap2020Demo.Core;
using Uaic.Tap2020Demo.Core.Services;
using Uaic.Tap2020Demo.DataAccess.Repositories;

namespace Tap2020Demo.Web.Areas.BackOffice.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ICustomersService _customersService;

        public CustomersController(ICustomersService customersService)
        {
            _customersService = customersService;
        }

        [Authorize]
        public async Task<IActionResult> IndexAsync(SearchCustomersViewModel viewModel)
        {
            var results = await _customersService.SearchCustomersAsync(viewModel.SearchTerm);

            return View(new SearchCustomersViewModel
            {
                SearchTerm = viewModel.SearchTerm,
                Results = results
            });
        }

    }
}

src/Tap2020Demo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Tap2020Demo.Web.Models;

namespace Tap2020Demo.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Tap2020Demo.Web/Areas/Account/Views/Authentication/Login.cshtml
@model Tap2020Demo.Web.Areas.Account.Models.LoginViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="container">
    <div class="row">
        <div class="col-6">
            <form method="post" asp-controller="Authentication" asp-action="Login" asp-area="Account" asp-route-returnurl="@ViewData["ReturnUrl"]">
                <div class="text-danger">
                    <ul>
                        @foreach (var error in ViewData.ModelState.SelectMany(_ => _.Value.Errors))
                        {
                            <li>
                                @error.ErrorMessage
                            </li>
                        }
                    </ul>
                </div>
                <div class="form-group">
                    <label for="Username">Username</label>
                    <input type="email" class="form-control" name="Username">
                </div>
                <div class="form-group">
                    <label for="Password">Password</label>
                    <input type="password" class="form-control" name="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

src/Tap2020Demo.Web/Areas/BackOffice/Views/Customers/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model Tap2020Demo.Web.Areas.BackOffice.Models.SearchCustomersViewModel
<div class="container">
    <div class="row">
        <div class="col-9">
            <form asp-controller="Customers" asp-action="Index" asp-area="BackOffice" method="get">
                <div class="form-row">
                    <div class="col-10">
                        <input type="search" class="input-search-box" name="SearchTerm" value="@Model.SearchTerm" />
                    </div>
                    <div class="col-2">
                        <input type="submit" value="@Localizer["Search"]" />
                    </div>
                </div>
            </form>
        </div>
        <div class="col-3">
            @Html.ActionLink(Localizer["Create customer"].Value, "Create", "Customers", new { area = "BackOffice" })
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">@Localizer["Name"]</th>
                    <th scope="col">@Localizer["IdNo"]</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Results)
                {
                    <tr>
                        <td>
                            <span>@item.FullName</span>
                        </td>
                        <td>
                            <span>@item.IdNo</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/Tap2020Demo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Tap2020Demo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tap2020Demo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tap2020Demo.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Account" asp-controller="Authentication" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="BackOffice" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tap2020Demo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>